services:
    wsse.security.authentication.provider:
        class: Cowtent\RestBundle\Security\Authentication\Provider\WsseProvider
        arguments:
            - "" # User Provider
            - "%kernel.cache_dir%/security/nonces"
        public: false

    wsse.security.authentication.listener:
        class: Cowtent\RestBundle\Security\Firewall\WsseListener
        arguments: ["@security.token_storage", "@security.authentication.manager", "@logger"]
        tags:
            - { name: monolog.logger, channel: wsse }
        public: false

    wsse.kernel.listener.exception:
        class: Cowtent\RestBundle\Listener\KernelExceptionListener
        arguments: ["@logger"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
